556 remove on2 operation from numberedobjectcollection
idaholab/MontePy pull request #563
Opened 2024-10-02 16:03 UTC by MicahGale

# Description

Please include a summary of the change and which issue is fixed if applicable. Please also include relevant motivation and context.

Fixes # (issue)

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-10-03 13:08 UTC, MicahGale commented
This depends on #539

2024-10-04 15:56 UTC, MicahGale commented
There is still an O(N^2) call to `.numbers` for some reason.

2024-10-07 12:53 UTC, MicahGale commented
I can't replicate this O(N^2) behavior. I wonder if the wrong version of MontePy was used in the test.

2024-10-08 21:33 UTC, MicahGale commented
Upon further examination this was a problem with my tests. If you look at the profile results in the CI, `numbers` doesn't even show up and `append` is very low on the list. So I think we can say this was solved.

2024-10-10 18:20 UTC, tjlaboss requested changes

2024-10-10 18:20 UTC, tjlaboss commented on montepy/numbered_object_collection.py
> +        """ """
empty docstring

2024-10-10 18:20 UTC, tjlaboss commented on montepy/numbered_object_collection.py
> +            nums = set(self.__num_cache.keys())
```python
nums = set(self.__num_cache)
```

2024-10-10 18:20 UTC, tjlaboss commented
Two small changes to make.

2024-10-10 18:59 UTC, MicahGale commented on montepy/numbered_object_collection.py
> +        """ """
I like those.

2024-10-11 15:31 UTC, MicahGale commented
No change in memory usage (duh), but went from 27.6 seconds to 26.7 seconds for this improvement. This is a 3% reduction for the "big model". Though this is a low cost O(N^2) operation, and the saving should scale accordingly.

2024-10-15 21:25 UTC, tjlaboss approved these changes

2024-10-15 21:30 UTC, merged